export const data = [
  {
    id: 1,
    name: 'shirt',
    description: 'The first product',
    category: 'clothe',
    price: 23.8,
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    inStock: [0, 3, 5, 6, 7],
    fastDelivery: false,
    ratings: [1, 2, 3, 4, 5],
  },
  {
    id: 2,
    name: 'trekas',
    description: 'The second product',
    category: 'shoe',
    price: 35.5,
    image:
      'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
    inStock: [0, 3, 5, 6, 7],
    fastDelivery: true,
    ratings: [1, 2, 3, 4, 5],
  },
  {
    id: 3,
    name: 'chain',
    description: 'The third product',
    category: 'jwellery',
    price: 29.3,
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    inStock: [0, 3, 5, 6, 7],
    fastDelivery: true,
    ratings: [1, 2, 3, 4, 5],
  },
  {
    id: 4,
    name: 'uniform',
    description: 'The fourth product',
    category: 'clothe',
    price: 45.2,
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    inStock: [0, 3, 5, 6, 7],
    fastDelivery: false,
    ratings: [1, 2, 3, 4, 5],
  },
  {
    id: 5,
    name: 'ring',
    description: 'The fifth product',
    category: 'jwellery',
    price: 52.1,
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    inStock: [0, 3, 5, 6, 7],
    fastDelivery: true,
    ratings: [1, 2, 3, 4, 5],
  },
  {
    id: 6,
    name: 'ring',
    description: 'The fifth product',
    category: 'jwellery',
    price: 52.1,
    image: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
    inStock: [0, 3, 5, 6, 7],
    fastDelivery: true,
    ratings: [1, 2, 3, 4, 5],
  },
];
